# Generated by Django 4.0.5 on 2022-06-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columnapi', '0001_initial'),
        ('boardapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapi.board')),
                ('column_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columnapi.column')),
            ],
        ),
    ]
