# Generated by Django 4.0.5 on 2022-06-06 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0001_initial'),
        ('columnapi', '0001_initial'),
        ('boardcolumnapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcolumnrelation',
            name='board_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boardapi.board'),
        ),
        migrations.AlterField(
            model_name='boardcolumnrelation',
            name='column_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='columnapi.column'),
        ),
    ]
