# Generated by Django 4.0.5 on 2022-06-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0006_board_created_at_alter_board_user'),
        ('columnapi', '0003_remove_column_board'),
        ('boardcolumnapi', '0003_alter_boardcolumnrelation_board_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardColumnRelation',
            new_name='BoardColumn',
        ),
    ]
