# Generated by Django 4.0.5 on 2022-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0002_remove_board_columns'),
        ('columnapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ManyToManyField(blank=True, related_name='board_column', to='boardapi.board'),
        ),
    ]
