# Generated by Django 4.0.5 on 2022-06-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='columns',
        ),
    ]
