# Generated by Django 4.0.5 on 2022-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('columnapi', '0003_remove_column_board'),
        ('boardapi', '0002_remove_board_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='columns',
            field=models.ManyToManyField(blank=True, to='columnapi.column'),
        ),
    ]
