# Generated by Django 4.0.5 on 2022-06-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0003_board_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='columns',
        ),
    ]
