# Generated by Django 4.0.5 on 2022-06-03 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('columnapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.BooleanField()),
                ('index', models.IntegerField()),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columnapi.column')),
            ],
        ),
    ]
