# Generated by Django 4.0.5 on 2022-06-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0001_initial'),
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boardapi.board'),
            preserve_default=False,
        ),
    ]
