# Generated by Django 4.0.5 on 2022-06-08 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columnapi', '0001_initial'),
        ('boardapi', '0001_initial'),
        ('taskapi', '0002_task_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_board', to='boardapi.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_column', to='columnapi.column'),
        ),
    ]
