# Generated by Django 4.0.5 on 2022-06-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0001_initial'),
        ('columnapi', '0001_initial'),
        ('taskapi', '0003_alter_task_board_alter_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_task', to='boardapi.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_task', to='columnapi.column'),
        ),
    ]
