# Generated by Django 4.0.5 on 2022-06-08 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardapi', '0003_board_columns'),
        ('columnapi', '0003_remove_column_board'),
        ('taskapi', '0004_alter_task_board_alter_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardapi.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='columnapi.column'),
        ),
    ]
